name: Python tests

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install tox and any other packages
        run: pip install --user poetry tox
      - name: Run tox
        # Run tox flake8 only
        run: tox -e flake8

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install --user poetry tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
